name: tests

on: [push, pull_request]

jobs:
  python-38-39:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9"]
        numpy-version: ["1.19.5", "1.20.3", "1.21.6"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependences
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install wavio
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest

  python-310:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
        numpy-version: ["1.21.6", "1.22.4", "1.23.4"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependences
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install wavio
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest

  python-311:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        numpy-version: ["1.23.4"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependences
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install wavio
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest
