name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
        numpy-version: [1.17.5, 1.18.4]

    steps:
    - uses: actions/checkout@v1
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependences
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install wavio
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        # cd ../..
        # pwd
        # export LOCATION=`python -c "import wavio, os; print(os.path.dirname(wavio.__file__))"`
        # echo $LOCATION
        # python -m pytest $LOCATION
        python -m pytest
